Repository react-appwrite/react-appwrite, pull requests merged in 2023-04, with the labels that each got.

#25 feat: Add remaining storage hooks
  example/app/storage/page.tsx
  example/package-lock.json
  example/package.json
  src/storage/README.md
  src/storage/index.ts
  src/storage/types.ts
  src/storage/useBucket.ts
  src/storage/useFilePreview.ts
  src/storage/useFileUpload.ts
  src/storage/useFileView.ts
Labels: enhancement, service: storage

#24 Add eslint
  .eslintrc.json
  .gitattributes
  .github/workflows/lint.yml
  .husky/pre-commit
  .vscode/settings.json
  package-lock.json
  package.json
  src/next/index.ts
Labels: enhancement

#27 Add Vercel sponsorship
  README.md
  docs/logos/vercel.svg
Labels: documentation

#23 Convert mutations to queries where possible
  example/app/storage/page.tsx
  example/next.config.mjs
  src/storage/useFile.ts
  src/storage/useFileDownload.ts
  src/storage/useFileUpdate.ts
  src/storage/useFileUpload.ts
  src/storage/useFileView.ts
Labels: enhancement

#19 feat: remaining team hooks (7/10)
  example/app/teams/[teamId]/page.tsx
  example/app/teams/page.tsx
  example/package-lock.json
  example/package.json
  src/account/useAnonymousSignIn.ts
  src/teams/index.ts
  src/teams/useTeamCreate.ts
  src/teams/useTeamCreateMembership.ts
  src/teams/useTeamDelete.ts
  src/teams/useTeamMembers.ts
  src/teams/useTeamUpdate.ts
  src/teams/useTeamUpdateMembershipRoles.ts
  src/teams/useTeams.ts
Labels: enhancement, service: teams

#37 useCreateDocument
  example/app/databases/page.tsx
  src/databases/index.ts
  src/databases/useDocumentCreate.ts
Labels: enhancement
